
# Build and autotest script for CCiA.
# http://travis-ci.org
sudo: required
dist: xenial
language: cpp

matrix:
fast_finish: true
include:
  # Ubuntu 16.04
  # GCC
  - os: linux
    compiler: gcc
    env: UBUNTU=16.04 COMPILER=gcc-5
  # Clang
  - os: linux
    compiler: clang
    env: UBUNTU=16.04 COMPILER=clang-3.8

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo add-apt-repository -y ppa:kzemek/boost
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-5
  - sudo apt-get install -y g++-5
  - sudo apt-get install -y clang-3.8
  - sudo apt-get install -y clang++-3.8
  - sudo apt-get install -y libboost-dev
  - export CC=gcc-5
  - echo $CC
  - export CXX=g++-5
  - echo $CXX

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make -j4
